server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://euk1.com:7901/eureka/

spring:
  application:
    name: zuulserver
  #zipkin
  zipkin:
    base-url: http://localhost:9411/
  #采样比例1
  sleuth:
    sampler:
      rate: 1
  boot:
    admin:
      client:
        #SpringBootAdmin 地址
        url: http://localhost:81

#日志
logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG


#监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
