server:
  port: 90

spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/GALAace/spring-cloud-config-center.git #\u914D\u7F6E\u6587\u4EF6\u6240\u5728\u7684Git\u4ED3\u5E93\u5730\u5740
          default-label: master #\u914D\u7F6E\u6587\u4EF6\u5206\u652F
          search-paths: configs  #\u914D\u7F6E\u6587\u4EF6\u6240\u5728\u76EE\u5F55
#          username: Git\u8D26\u53F7
#          password: Git\u5BC6\u7801

eureka:
  client:
    service-url:
      defaultZone: http://euk1.com:7901/eureka/
