server:
  port: 90

spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/GALAace/spring-cloud-config-center.git #配置文件所在的Git仓库地址
          default-label: master #配置文件分支
          search-paths: configs  #配置文件所在目录
#          username: Git账号
#          password: Git密码
  boot:
    admin:
      client:
        #SpringBootAdmin 地址
        url: http://localhost:81


eureka:
  client:
    service-url:
      defaultZone: http://euk1.com:7901/eureka/


#监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
